import 'dart:convert';
import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

import 'tables/application_table.dart';
import 'tables/consistency_log_table.dart';
import 'tables/dsa_log_table.dart';
import 'tables/enums.dart';
import 'tables/insight_dismissal_table.dart';
import 'tables/interview_prep_table.dart';
import 'tables/notes_table.dart';
import 'tables/resume_table.dart';
import 'tables/series_table.dart';
import 'tables/session_category_table.dart';
import 'tables/study_phase_table.dart';
import 'tables/task_table.dart';
import 'tables/time_session_table.dart';
import 'tables/upcoming_interview_table.dart';
import 'tables/user_profile_table.dart';

// DAO part files — generated by build_runner
part 'app_database.g.dart';
part 'daos/user_profile_dao.dart';
part 'daos/task_dao.dart';
part 'daos/application_dao.dart';
part 'daos/consistency_dao.dart';
part 'daos/dsa_dao.dart';
part 'daos/notes_dao.dart';
part 'daos/series_dao.dart';
part 'daos/study_phase_dao.dart';
part 'daos/resume_dao.dart';
part 'daos/interview_prep_dao.dart';
part 'daos/insight_dismissal_dao.dart';
part 'daos/time_session_dao.dart';
part 'daos/upcoming_interview_dao.dart';

@DriftDatabase(
  tables: [
    UserProfileTable,
    StudyPhaseTable,
    SeriesTable,
    TaskTable,
    DsaLogTable,
    ApplicationTable,
    ApplicationStatusHistoryTable,
    ConsistencyLogTable,
    ResumeTable,
    InterviewPrepTable,
    NoteTable,
    NoteTagTable,
    InsightDismissalTable,
    SessionCategoryTable,
    TimeSessionTable,
    UpcomingInterviewTable,
  ],
  daos: [
    UserProfileDao,
    TaskDao,
    ApplicationDao,
    ConsistencyDao,
    DsaDao,
    NotesDao,
    SeriesDao,
    StudyPhaseDao,
    ResumeDao,
    InterviewPrepDao,
    InsightDismissalDao,
    TimeSessionDao,
    UpcomingInterviewDao,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());
  AppDatabase.forTesting(super.e);

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll();
          // Seed built-in categories on fresh install
          await into(sessionCategoryTable).insert(
            SessionCategoryTableCompanion.insert(
              name: 'Study',
              colorHex: '#5FA070',
              isBuiltIn: const Value(true),
            ),
          );
          await into(sessionCategoryTable).insert(
            SessionCategoryTableCompanion.insert(
              name: 'Entertainment',
              colorHex: '#F2954F',
              isBuiltIn: const Value(true),
            ),
          );
        },
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            await m.addColumn(taskTable, taskTable.parentTaskId);
            await m.addColumn(taskTable, taskTable.linkedApplicationId);
            await m.createTable(sessionCategoryTable);
            await m.createTable(timeSessionTable);
            // Seed built-in categories on migration
            await into(sessionCategoryTable).insert(
              SessionCategoryTableCompanion.insert(
                name: 'Study',
                colorHex: '#5FA070',
                isBuiltIn: const Value(true),
              ),
            );
            await into(sessionCategoryTable).insert(
              SessionCategoryTableCompanion.insert(
                name: 'Entertainment',
                colorHex: '#F2954F',
                isBuiltIn: const Value(true),
              ),
            );
          }
          if (from < 3) {
            await m.createTable(upcomingInterviewTable);
            await m.addColumn(timeSessionTable, timeSessionTable.durationSeconds);
            await m.addColumn(timeSessionTable, timeSessionTable.activityRefType);
            await m.addColumn(timeSessionTable, timeSessionTable.lastHeartbeatAt);
          }
        },
      );

  /// Opens (or creates) the SQLite database via drift_flutter.
  /// Uses an in-background isolate for heavy queries automatically.
  static QueryExecutor _openConnection() {
    return driftDatabase(name: 'ascent_db');
  }
}
